#ifndef XENA_LOG_HH
#define XENA_LOG_HH

#include "soil/Log.hh"

#define XENA_LOG_INIT(x) SOIL_LOG_INIT(x)

#define XENA_TRACE SOIL_TRACE
#define XENA_DEBUG SOIL_DEBUG
#define XENA_INFO  SOIL_INFO
#define XENA_WARNING SOIL_WARNING
#define XENA_ERROR SOIL_ERROR
#define XENA_FATAL SOIL_FATAL
#define XENA_PDU SOIL_PDU
#define XENA_CUSTOM SOIL_CUSTOM


#endif
